version: '2'

services:
  faktory:
    image: contribsys/faktory
    command: /faktory -b 0.0.0.0:7419 -e production
    volumes:
      - faktory-data:/var/lib/faktory
    environment:
      FAKTORY_PASSWORD: "password"

  hpr:
    image: icyleafcn/hpr
    ports:
      - 8848:8848
    volumes:
      - ./config:/app/config
      - hpr-repositories:/app/repositories
    environment:
      FAKTORY_URL: tcp://:password@faktory:7419
      FAKTORY_PROVIDER: FAKTORY_URL
      HPR_SSH_HOST: localhost
      HPR_SSH_PORT: 10022
    depends_on:
      - faktory
    networks:
      - tier

volumes:
  faktory-data:
  hpr-repositories:
