version: '2'

services:
  faktory:
    image: contribsys/faktory
    command: /faktory -b 0.0.0.0:7419 -e production
    ports:
      - 7419:7419
      - 7420:7420
    volumes:
      - faktory-data:/var/lib/faktory
    environment:
      FAKTORY_PASSWORD: "password"
  hpr:
    build: ../../
    image: icyleafcn/hpr
    ports:
      - 8848:8848
    volumes:
      - ./config:/app/config
      - ./repositories:/app/repositories
    environment:
      FAKTORY_URL: tcp://:password@faktory:7419
      FAKTORY_PROVIDER: FAKTORY_URL
    depends_on:
      - faktory

volumes:
  faktory-data:
