version: '2'

services:
  hpr:
    image: icyleafcn/hpr
    ports:
      - 8848:8848
    volumes:
      - ./config:/app/config
      - hpr-repositories:/app/repositories
    environment:
      REDIS_URL: tcp://redis:6379
      REDIS_PROVIDER: REDIS_URL

      HPR_SSH_HOST: gitlab
      HPR_SSH_PORT: 22
    depends_on:
      - redis
    networks:
      - hpr
  redis:
    image: redis:alpine
    networks:
      - hpr

volumes:
  hpr-repositories:

networks:
  hpr:
    external:
      name: selfhost_gitlab
